services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      # Пробрасываем сокет Docker, чтобы proxy мог слушать события (создание/удаление контейнеров)
      # :ro сокет только на чтение (безопасность)
      - /var/run/docker.sock:/tmp/docker.sock:ro

  backend:
    build: ./backend
    environment:
      # Nginx-proxy автоматически создаст маршрут для этого домена
      - VIRTUAL_HOST=backend.test
      # Указываем, на какой порт внутри контейнера слать трафик (т.к. наш Python работает на 8080)
      - VIRTUAL_PORT=8080